# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180127_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
