# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_check_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='duration',
        ),
        migrations.AddField(
            model_name='check',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
    ]
